[package]
name = "oxcc"
version = "0.0.1"
authors = ["jonlamb-gh <lamb.jon.io@gmail.com>"]

[dependencies]
cortex-m-semihosting = "0.3.0"
panic-semihosting = "0.3.0"
#nb = "0.1.1"

[dependencies.cortex-m]
version = "0.5.2"
features = ["const-fn"]

[dependencies.cortex-m-rt]
version = "0.5.1"
features = ["device"]

[dependencies.stm32f7]
version = "0.2.2"
features = ["stm32f7x7", "rt"]

[dependencies.nucleo-f767zi]
version = "0.0.1"
git = "https://github.com/jonlamb-gh/nucleo-f767zi.git"
branch = "devel"
features = ["rt"]

[profile.release]
codegen-units = 1 # better optimizations
lto = true # better optimizations
